### PR TITLE
Add tyvik/geopuzzle repo

### PR DESCRIPTION
**Pull request by TyVik**
I'm going to add more details later for "Contributing" block.

### CODE REVIEW

**Comment by TyVik** [comment]
I've updated "Contributing" section.
Also, I added some featured maps.

**Comment by TyVik** [comment]
I fixed but is it possible to keep more than one feature map?

**Comment by TyVik** [comment]
Could you please merge this PR?

I've finished it for now and I'm waiting for #212 :) No rush of course - I subscribed on this issue and will receive a reminder when the ticket will be closed.

**Comment by ramonh** [comment]
On it. Thanks again and welcome to Port! 🚢

**Pull request merged**
