### PR TITLE
Added ChatCube with CodeSee maps

### PR DESCRIPTION
**Pull request by avneesh0612**
I have added my project ChatCube and the CodeSee map with it :)

### CODE REVIEW

**Review by ramonh — APPROVED** [review]
@avneesh0612 This is beautiful, thank you so much for adding a map! 🎉

**Comment by ramonh** [comment]
Oh oops, sorry, @avneesh0612, it seems this branch is a little out-of-date.

Did you branch off of `main`? Could you please try rebasing and see if it fixes the conflicts?

**Comment by avneesh0612** [comment]
Oh, I just synced all the changes @ramonh . Lemme just refork and try

**Comment by ramonh** [comment]
That'd be great, thank you so much!

**Comment by avneesh0612** [comment]
Made a new [PR](https://github.com/Codesee-io/oss-port/pull/91) @ramonh. You can see it [here](https://github.com/Codesee-io/oss-port/pull/91)

**Comment by ramonh** [comment]
Merged, thank you so much! I'll go ahead and close this one.

**Comment by avneesh0612** [comment]
okay cool

**Pull request closed without merging**
