### PR TITLE
Add project Meditate-app

### PR DESCRIPTION
**Pull request by akshat157**
Hi! I have added my project https://github.com/akshat157/meditate-app with a CodeSee Map. Still new to sharing my projects in other communities so suggestions are welcome. :)

### CODE REVIEW

**Comment by deammer** [comment]
Hi @akshat157 welcome to OSS Port! The page you created looks marvelous, we're so excited to publish it on the site!

Fyi, I fixed an issue in your markup and pushed to your branch to save you some time. Our build system expects `<br>` tags to be self-closing, so I modifed them from `<br>` to `<br/>`.

**Review by deammer — APPROVED** [review]
💯 🚀

**Comment by akshat157** [comment]
Hi @deammer! Thanks for the words of appreciation!

I have an obsession with closing the `<br />` tags. Not sure how or where I missed these lol.
However, thank you for the fix! Happy to be part of another OSS community! :D

**Comment by jleven** [comment]
@akshat157 -- Thank you again for listing your project, and for listing your CodeSee Map on our [showcase page](https://app.codesee.io/maps/community). I'm thrilled to tell you the team absolutely loves your map, and we've selected it to be one of our first "Featured Projects" on that page!

And thank you again for being part of the OSS Port community.

**Pull request merged**
