### PR TITLE
Add WordPress Vulnerability Check project

### PR DESCRIPTION
**Pull request by umutphp**

### CODE REVIEW

**Review by ramonh — APPROVED** [review]
Thank you so much for your contribution, @umutphp 

This looks fantastic! I'm such a big fan of non-code contributions and I love that you invite them here!

Welcome to the Port!

**Comment by ramonh** [comment]
Oh, woops! Looks like I can't seem to rebase and merge your branch.

Could it be you need to make some tweaks to the git history? Could you please try rebasing against the latest version of `main`?

Thanks in advance!

**Comment by ramonh** [comment]
Sorry @umutphp, just following up as I saw your emoji reaction 😅 

Could you please rebase your branch against the current version of `main` so we can merge this? I'm afraid there are conflicts.

Thanks in advance!

**Comment by umutphp** [comment]
I think I made something very wrong :). Let me create the PR from scratch :)

**Pull request closed without merging**
