### PR TITLE
Add Utilobot to the list of Projects

### PR DESCRIPTION
**Pull request by DefCon-007**

### CODE REVIEW

**Review by ramonh — CHANGES_REQUESTED** [review]
Looking great overall, @DefCon-007, thank you!

One thing I'd love to request if you could perhaps add some contribution guidelines, maybe a Code of Conduct?

Take a look at ours here:
https://www.oss-port.com/Codesee-io/oss-port#contributing

https://github.com/Codesee-io/oss-port/blob/main/code_of_conduct.md

If you have any questions, please let me know! We're very interested in getting folks onboarded as smoothly as possible :)

**Review by ramonh — APPROVED** [review]
This is beautiful, thank you! 

Welcome to Port 🚢

**Comment by DefCon-007** [comment]
Hey @ramonh, added contribution guidelines, I am not adding a Code of Conduct as of now, will add it in future. Hope that's fine.

**Comment by ramonh** [comment]
All good, thanks! 

I can personally highly recommend adding a [code of conduct](https://www.contributor-covenant.org/). As a person looking for a project myself, one of the first things I look for is one. 

Until then, merged!

**Pull request merged**
